apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "my-app-back-end-springboot-app.fullname" . }}-configmap
data:
  application.properties: |
    server.port=9999
    spring.redis.host=three-tier-app-back-end-db-redis
    spring.redis.port=6379            