kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "my-app-back-end-db-redis.fullname" . }}-configmap
data:
  redis.conf: |-
    dir /srv
    port 6379
    bind 0.0.0.0
    appendonly yes
    daemonize no
    # protected-mode no
    # timeout 0
    pidfile /srv/redis-6379.pid