{{- if .Values.ingress.enabled -}}
{{- $fullName := include "my-app-back-end-springboot-app.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
# API Version
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  # Ingress Object Name 
  name:  {{ $fullName }}
  # Namespace 
spec:
  rules:
   # Rule Host match  /etc/hosts
   # host 80 443 
   {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}         
      http:
        paths:       
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}   
            backend:           
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $svcPort }}
              {{- end }}       
   {{- end }}                  
{{- end }}                                         