apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-app-front-end-react-app.fullname" . }}
  labels:
    {{- include "my-app-front-end-react-app.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "my-app-front-end-react-app.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 80