apiVersion: v1
kind: Service
metadata:
  name:  {{ .Values.global.redisServiceName}}
  labels:
    {{- include "my-app-back-end-db-redis.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.global.redisServicePort}}
      targetPort: {{ .Values.service.port }}
      name: tcp
  selector:
    {{- include "my-app-back-end-db-redis.selectorLabels" . | nindent 4 }}
